- name: Pull and Run docker image
  hosts: remoteserver
  tasks:
    - name: Pull ameyaameya/scientific_calculator
      docker_image:
        name: ameyaameya/scientific_calculator
        source: pull
